BOARD := arduino:avr:uno
#BOARD := attiny:avr:ATtinyX5:cpu=attiny85,clock=internal8
ARDDUDE_OPTIONS := -l cr -o raw -d
PORT := /dev/ttyUSB0
LIBRARY_PATH := /home/pif/GitHub/piif /home/pif/GitHub/piif/ArduinoTools
